controller_manager:
  ros__parameters:
    update_rate: 100
    use_sim_time: true

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    effort_controller:
      type: effort_controllers/JointGroupEffortController

velocity_controller:
  ros__parameters:
    joints:
      - left_wheel_joint
      - right_wheel_joint

effort_controller:
  ros__parameters:
    joints:
      - left_wheel_joint
      - right_wheel_joint
